const messages = {
  en: {
    translations: {
      tabNavigation: {
        home: 'Home',
        favorites: 'Favorites',
        settings: 'Settings',
      },
      settingsPage: {
        selectLanguage: {
          label: 'Language',
          pt: 'Português',
          en: 'English',
        },
      },
      homePage: {
        releases: 'Releases',
        favorites: 'Favorites',
        recommendations: {
          title: 'Recommendations',
          noRecommendations: 'Nothing here yet...',
          subtitle: 'Generated by ChatGPT from your favorites list',
        },
      },
      moviePage: {
        favoriteButton: {
          add: 'Add',
          remove: 'Remove',
        },
        synopsis: 'Synopsis',
        director: 'Director',
        budget: 'Budget',
        available: 'Available on',
        notAvailable: 'Not available',
        cast: 'Cast',
        videos: 'Videos',
      },
    },
  },
};

export { messages };
