const messages = {
  en: {
    translations: {
      tabNavigation: {
        home: 'Home',
        favorites: 'Favorites',
        settings: 'Settings',
      },
      settingsPage: {
        selectLanguage: {
          label: 'Language',
          pt: 'Português',
          en: 'English',
        },
      },
      header: {
        settings: 'Settings',
        logout: 'Logout',
      },
      homePage: {
        releases: 'Releases',
        favorites: 'Favorites',
        recommendations: {
          title: 'Recommendations',
          noRecommendations: 'Nothing here yet...',
          subtitle: 'Generated by ChatGPT from your favorites list',
        },
      },
      moviePage: {
        favoriteButton: {
          add: 'Add',
          remove: 'Remove',
        },
        synopsis: 'Synopsis',
        director: 'Director',
        budget: 'Budget',
        available: 'Available on',
        notAvailable: 'Not available',
        cast: 'Cast',
        videos: 'Videos',
      },
      genres: {
        action: 'Action',
        adventure: 'Adventure',
        animation: 'Animation',
        comedy: 'Comedy',
        crime: 'Crime',
        documentary: 'Documentary',
        drama: 'Drama',
        family: 'Family',
        fantasy: 'Fantasy',
        history: 'History',
        horror: 'Horror',
        music: 'Music',
        mystery: 'Mystery',
        romance: 'Romance',
        scienceFiction: 'Science Fiction',
        tvMovie: 'TV Movie',
        thriller: 'Thriller',
        war: 'War',
        western: 'Western',
      },
    },
  },
};

export { messages };
